-- ============================================================
-- 预警规则 + 预警事件种子（南昌）
-- 时间戳与 TDengine seed 脚本制造的异常时段对齐，
-- 支撑「告警→溯源→相似案例」演示闭环
-- ============================================================

-- ==============================================
-- 1. alert_rules：5 条典型规则
-- ==============================================
INSERT INTO alert_rules (
    rule_name, rule_type, station_ids, metric_codes,
    conditions, alert_level, notification_channels, is_enabled
) VALUES
(
    'pH 偏酸告警',
    'threshold',
    ARRAY[]::uuid[],
    ARRAY['ph']::varchar[],
    '{"operator":"<","threshold":6.0,"duration_minutes":30}'::jsonb,
    'high',
    ARRAY['app','sms']::varchar[],
    true
),
(
    '溶解氧偏低',
    'threshold',
    ARRAY[]::uuid[],
    ARRAY['do']::varchar[],
    '{"operator":"<","threshold":5.0,"duration_minutes":60}'::jsonb,
    'medium',
    ARRAY['app']::varchar[],
    true
),
(
    '氨氮超标（Ⅲ类）',
    'threshold',
    ARRAY[]::uuid[],
    ARRAY['nh3_n']::varchar[],
    '{"operator":">","threshold":1.0,"duration_minutes":30}'::jsonb,
    'high',
    ARRAY['app','sms','email']::varchar[],
    true
),
(
    '高锰酸盐指数超标',
    'threshold',
    ARRAY[]::uuid[],
    ARRAY['codmn']::varchar[],
    '{"operator":">","threshold":6.0,"duration_minutes":30}'::jsonb,
    'high',
    ARRAY['app','sms']::varchar[],
    true
),
(
    '蓝绿藻密度预警（鄱阳湖沿岸）',
    'threshold',
    (SELECT ARRAY_AGG(id) FROM stations WHERE station_code IN ('NC_RW005','NC_RW004')),
    ARRAY['blue_green_algae']::varchar[],
    '{"operator":">","threshold":10000,"duration_minutes":15}'::jsonb,
    'critical',
    ARRAY['app','sms','email','wechat']::varchar[],
    true
)
ON CONFLICT DO NOTHING;

-- ==============================================
-- 2. alerts：15 条预警事件
-- ==============================================
INSERT INTO alerts (
    alert_code, station_id, alert_type, alert_level,
    title, description, metrics, pollution_type, source_analysis,
    status, created_at
) VALUES
-- 活跃/待处理
('ALERT-2026-0001',
    (SELECT id FROM stations WHERE station_code='NC_IP001'),
    'threshold', 'high',
    '南昌经开区工业站 NH3-N 超标',
    '过去 30 分钟 NH3-N 持续 > 1.8 mg/L，疑似上游工业废水偷排',
    '{"metric":"nh3_n","peak_value":2.38,"avg_value":1.96,"standard":1.0}'::jsonb,
    'industrial_wastewater',
    '{"upstream_candidates":[{"source_id":"PS_NC_007","name":"某汽车零部件厂","distance_km":1.2,"probability":0.78}],"similar_cases":["NC-2024-003"]}'::jsonb,
    'pending',
    CURRENT_TIMESTAMP - INTERVAL '25 minutes'),
('ALERT-2026-0002',
    (SELECT id FROM stations WHERE station_code='NC_RW005'),
    'anomaly', 'critical',
    '鄱阳湖南岸湖滨站蓝绿藻暴发预警',
    '蓝绿藻密度达 15800 cells/mL，叶绿素 a 同步升高至 18.5 μg/L',
    '{"metric":"blue_green_algae","peak_value":15800,"chlorophyll":18.5}'::jsonb,
    'algae_bloom',
    '{"env_factors":{"water_temp":28.6,"tn_tp_ratio":16.2},"similar_cases":["NC-2024-007"]}'::jsonb,
    'confirmed',
    CURRENT_TIMESTAMP - INTERVAL '2 hours'),
('ALERT-2026-0003',
    (SELECT id FROM stations WHERE station_code='NC_RW004'),
    'anomaly', 'high',
    '湾里象湖乡村站 CODMn 异常升高',
    'LSTM 重构误差突增，CODMn 偏离 3σ，达 8.6 mg/L',
    '{"metric":"codmn","peak_value":8.6,"reconstruction_error":0.187}'::jsonb,
    'organic_pollution',
    '{"upstream_stations":["NC_BS001","NC_BS003"],"similar_cases":["NC-2024-003"]}'::jsonb,
    'pending',
    CURRENT_TIMESTAMP - INTERVAL '5 hours'),
('ALERT-2026-0004',
    (SELECT id FROM stations WHERE station_code='NC_IP003'),
    'threshold', 'medium',
    '进贤工业园 TP 偏高',
    '总磷连续 2 小时 > 0.15 mg/L，可能来自上游农业径流',
    '{"metric":"total_p","avg_value":0.18,"standard":0.05}'::jsonb,
    'agricultural_runoff',
    '{"upstream_land_use":"水稻种植","similar_cases":["NC-2024-005"]}'::jsonb,
    'processing',
    CURRENT_TIMESTAMP - INTERVAL '8 hours'),
('ALERT-2026-0005',
    (SELECT id FROM stations WHERE station_code='NC_BS001'),
    'threshold', 'medium',
    '赣江入鄱阳湖断面 CODCr 升高',
    'CODCr 达 28 mg/L，略高于Ⅲ类限值',
    '{"metric":"codcr","peak_value":28,"standard":20}'::jsonb,
    'organic_pollution',
    '{"similar_cases":["NC-2024-003"]}'::jsonb,
    'confirmed',
    CURRENT_TIMESTAMP - INTERVAL '12 hours'),
-- 已解决
('ALERT-2025-0995',
    (SELECT id FROM stations WHERE station_code='NC_WS002'),
    'threshold', 'high',
    '罗家集赣江中支水源地 pH 异常偏酸',
    'pH 降至 5.6，持续 40 分钟',
    '{"metric":"ph","min_value":5.6,"standard":6.0}'::jsonb,
    'industrial_wastewater',
    '{"upstream_candidates":[{"source_id":"PS_NC_015","name":"安义铝型材表面处理园","distance_km":2.4,"probability":0.62}]}'::jsonb,
    'resolved',
    CURRENT_TIMESTAMP - INTERVAL '2 days'),
('ALERT-2025-0994',
    (SELECT id FROM stations WHERE station_code='NC_BS002'),
    'threshold', 'medium',
    '抚河入鄱阳湖断面浊度升高',
    '降雨后浊度升至 180 NTU',
    '{"metric":"turbidity","peak_value":180,"standard":3.0}'::jsonb,
    'surface_runoff',
    '{"weather":"暴雨"}'::jsonb,
    'resolved',
    CURRENT_TIMESTAMP - INTERVAL '3 days'),
('ALERT-2025-0993',
    (SELECT id FROM stations WHERE station_code='NC_WS001'),
    'threshold', 'low',
    '象湖水源地 DO 波动',
    '溶解氧短时降至 4.8 mg/L',
    '{"metric":"do","min_value":4.8,"standard":5.0}'::jsonb,
    NULL,
    '{"note":"自然波动可能性大"}'::jsonb,
    'resolved',
    CURRENT_TIMESTAMP - INTERVAL '5 days'),
('ALERT-2025-0992',
    (SELECT id FROM stations WHERE station_code='NC_BS003'),
    'anomaly', 'high',
    '潦河入赣江断面 NH3-N 突增',
    '模型检测到短时尖峰异常',
    '{"metric":"nh3_n","peak_value":2.1,"reconstruction_error":0.22}'::jsonb,
    'domestic_sewage',
    '{"similar_cases":["NC-2024-002"]}'::jsonb,
    'resolved',
    CURRENT_TIMESTAMP - INTERVAL '8 days'),
('ALERT-2025-0991',
    (SELECT id FROM stations WHERE station_code='NC_BS004'),
    'threshold', 'medium',
    '锦江入赣江断面浊度持续偏高',
    '浊度连续 4 小时 > 50 NTU',
    '{"metric":"turbidity","avg_value":62}'::jsonb,
    'surface_runoff',
    '{}'::jsonb,
    'resolved',
    CURRENT_TIMESTAMP - INTERVAL '10 days'),
-- 已忽略
('ALERT-2025-0990',
    (SELECT id FROM stations WHERE station_code='NC_RW001'),
    'threshold', 'low',
    '安义潦河上游乡村站 pH 轻微波动',
    'pH 瞬时 6.1，持续不足 5 分钟',
    '{"metric":"ph","min_value":6.1}'::jsonb,
    NULL,
    '{"note":"误报（采样器维护）"}'::jsonb,
    'ignored',
    CURRENT_TIMESTAMP - INTERVAL '11 days'),
('ALERT-2025-0989',
    (SELECT id FROM stations WHERE station_code='NC_RW002'),
    'threshold', 'low',
    '进贤抚河乡村站电导率偏高',
    '电导率 1150 μS/cm',
    '{"metric":"conductivity","peak_value":1150}'::jsonb,
    NULL,
    '{"note":"本底值偏高"}'::jsonb,
    'ignored',
    CURRENT_TIMESTAMP - INTERVAL '14 days'),
-- 更早的历史告警
('ALERT-2024-0880',
    (SELECT id FROM stations WHERE station_code='NC_IP001'),
    'threshold', 'critical',
    '南昌经开区工业站 NH3-N 严重超标（NC-2024-003）',
    '2024年 5月实际案例：NH3-N 最高达 4.2 mg/L',
    '{"metric":"nh3_n","peak_value":4.2}'::jsonb,
    'industrial_wastewater',
    '{"case_id":"NC-2024-003","resolved_source":"上游某汽车零部件厂偷排，已查处"}'::jsonb,
    'resolved',
    '2024-05-08 14:30:00+08'),
('ALERT-2024-0750',
    (SELECT id FROM stations WHERE station_code='NC_RW005'),
    'anomaly', 'critical',
    '鄱阳湖南岸藻华事件（NC-2024-007）',
    '2024年 8月蓝绿藻密度峰值 28000 cells/mL',
    '{"metric":"blue_green_algae","peak_value":28000}'::jsonb,
    'algae_bloom',
    '{"case_id":"NC-2024-007","treatment":"启动曝气+生物调控"}'::jsonb,
    'resolved',
    '2024-08-05 10:15:00+08'),
('ALERT-2024-0620',
    (SELECT id FROM stations WHERE station_code='NC_RW004'),
    'threshold', 'high',
    '象湖水系青云谱段黑臭水体预警（NC-2024-009）',
    '2024年 10月 DO<2 mg/L，透明度 8cm',
    '{"do":1.8,"transparency":8}'::jsonb,
    'black_odor',
    '{"case_id":"NC-2024-009"}'::jsonb,
    'resolved',
    '2024-10-05 09:20:00+08')
ON CONFLICT (alert_code) DO NOTHING;
